// GENERATED by scripts/generate-shims.mjs — do not edit by hand.
// @ts-nocheck — React's runtime export list is wider than @types/react
// declares (internals, unstable_*). The shim must forward what actually
// exists at runtime, not what the published types admit to.
// Shared-dependency shim for 'react/jsx-runtime'.
export { default } from "react/jsx-runtime";
export {
  Fragment,
  jsx,
  jsxs,
} from "react/jsx-runtime";
