import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Manual rather than autogenerated — same reason as GameEngine's docs/sidebar.ts:
 * autogeneration takes its order from folder contents, and this project has too
 * few pages to need folders at all. Adding a page means adding it here.
 */
const sidebars: SidebarsConfig = {
  docs: ["index", "guide", "json-site-data", "css-contract"],
};

export default sidebars;
