/**
 * Writes the shared-dependency shim modules the import map points at.
 *
 * Generated rather than hand-written because React still ships CommonJS: a
 * plain `export * from "react"` re-exports nothing a bundler can see, which
 * fails silently — the build succeeds, the file is 100 bytes, and the page
 * dies on the first named import. Reading the real export list and emitting it
 * explicitly is the honest form of the same intent.
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const targets = [
  { specifier: "react", file: "react.ts" },
  { specifier: "react/jsx-runtime", file: "jsx-runtime.ts" },
  { specifier: "react-dom/client", file: "react-dom-client.ts" },
];

const identifier = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

for (const { specifier, file } of targets) {
  const namespace = await import(specifier);
  const names = Object.keys(namespace)
    .filter((name) => identifier.test(name) && name !== "default")
    .sort();
  const body = [
    "// GENERATED by scripts/generate-shims.mjs — do not edit by hand.",
    "// @ts-nocheck — React's runtime export list is wider than @types/react",
    "// declares (internals, unstable_*). The shim must forward what actually",
    "// exists at runtime, not what the published types admit to.",
    `// Shared-dependency shim for '${specifier}'.`,
    `export { default } from "${specifier}";`,
    `export {`,
    ...names.map((name) => `  ${name},`),
    `} from "${specifier}";`,
    "",
  ].join("\n");
  await writeFile(join(here, "..", "src", "shared", file), body, "utf8");
  console.log(`${file}: ${names.length} named exports`);
}
